### ISSUE TITLE
Component not giving correct date in sky-date-range-picker

### ISSUE THREAD

**Issue by abhishekmaheshwari1106** [blackbaud/skyux-datetime#209]
### Expected behavior
When we select an option in `sky-date-range-picker` we are not getting the correct date. It giving a calculated date as per the timezone.
### Actual behavior
When we select the "Yesterday" option it is giving the wrong date. In the sky-date-range-picker I selected "Yesterday", so it should give me 10th August 2020 but it is giving me 9th August 2020 as today is 11th August 2020.
![image](https://user-images.githubusercontent.com/61449153/90242314-6a43dd00-de4a-11ea-8772-e26fe4ba85d9.png)

Similarly, When I'm selecting "Last quarter", see the output which we get:
![image](https://user-images.githubusercontent.com/61449153/90242388-8fd0e680-de4a-11ea-9c9b-7937b3fa89ab.png)

### Steps to reproduce
Open the Blackbaud component documentation and search for sky date range picker component. (https://developer.blackbaud.com/skyux/components/date-range-picker)

In the given example select various options and see the output values.
Note: Change your system timezone to IST or something else.
### Impact

[AB#1552260](https://blackbaud.visualstudio.com/f565481a-7bc9-4083-95d5-4f953da6d499/_workitems/edit/1552260)

**Comment by Blackbaud-SteveBrush** [comment]
This appears to not be a problem with the source code, but with how `JSON.stringify` works; [it's converting the date to UTC](https://stackoverflow.com/questions/1486476/json-stringify-changes-time-of-date-because-of-utc) on the demo/code-example, but the actual date value of the form still reflects the user's timezone. We should update the demo to not use `JSON.stringify`, but the value coming from the form's `ngModel` should still reflect the user's timezone.
