### ISSUE TITLE
Date range picker and datepicker components do not support other locales

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux-datetime#38]
### Expected behavior

`SkyDateRangePickerComponent` and `SkyDatepickerComponent` should support locales other than `en-US`.

### Actual behavior

They only support `en-US`.

FYI: we recently added Angular 4's `intl` utility to our `SkyDatePipe` source.
https://github.com/blackbaud/skyux-datetime/pull/36

**Comment by Blackbaud-RobertDixon** [comment]
Any updates on this issue?  We believe it's the source of a customer bug we have that causes the browser to freeze.

**Comment by Blackbaud-AlexKingman** [comment]
This has been solved in a prior PR. Both the date picker and date range picker will support different locales. Also of note: @Blackbaud-RobertDixon 's customer bug (noted above) was caused by using a `moment` date as the model for the date picker. The fix here is to make sure and use `moment`s `.locale()` method to pass the browser's current locale before injecting the date into the datepicker component.

Closing as resolved.
