### ISSUE TITLE
Datepicker and timepicker button dropdowns on modal are cut off in Safari

### ISSUE THREAD

**Issue by Blackbaud-LouisPujol** [blackbaud/skyux-datetime#56]
### Expected behavior
The popover for the date and time pickers should pop out over the modal even if this would mean beyond the borders of the modal itself

### Actual behavior
They are cut off by the modal-content area

### Steps to reproduce
*Note: this only reproduces in Safari. Chrome, Edge and Firefox do not display this issue.
Have a modal component with a datepicker and/or timepicker
Open the dropdown by pushing the datepicker/timepicker button
The dropdown gets cut off by the modal

### Impact
This makes the calendar and time selector dropdowns useless as the user is not able to see the content in them.

Chrome:
<img width="710" alt="chrome" src="https://user-images.githubusercontent.com/7572597/58663142-739e6380-82f1-11e9-89c3-83686cbdf55b.png">

Firefox:
<img width="631" alt="firefox" src="https://user-images.githubusercontent.com/7572597/58663161-8022bc00-82f1-11e9-8695-570754771f39.png">

Safari:
<img width="622" alt="safari" src="https://user-images.githubusercontent.com/7572597/58663167-83b64300-82f1-11e9-9882-f3bc4d169f4d.png">

**Comment by Blackbaud-AlexKingman** [comment]
There have been some improvements to popover/dropdown layouts since this initial issue was filed. We re-ran this scenario again and cannot replicate with the latest versions of `@skyux/datetime@3.7.1`, and `@skyux/popovers@3.4.0`. Closing this issue - if you still are having problems with the latest versions of those libraries, please re-open.
